"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("users", [
      {
        id: 1,
        first_name: "abc",
        last_name: "Zen8labs",
        full_name: "abc Zen8labs",
        nick_name: "zenny",
        email: "zen8labs@gmail.com",
        phone: "03242332532",
        address: "Thon noi-Thuong Lam-My Duc-Ha Noi",
        password:
          "$2a$10$eMEyY0hhVqBGHASjqTtRH.I3jnhNGN0G2YlX49QW8w9Q8LhjyAQ6W",
        avatar: null,
        role_id: null,
        dob: null,
        deleted: false,
        blocked: false,
        socket: null,
        facebook_auth: null,
        google_auth: null,
        code: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        created_at: "2024-07-03T08:11:20.473Z",
        updated_at: "2024-07-03T08:11:20.473Z",
      },
      {
        id: 2,
        first_name: "Gia Bảo",
        last_name: "Trần",
        full_name: "Gia Bảo Trần",
        nick_name: "Quân Trịnh Hoàng",
        email: "quan20028a3kb@gmail.com",
        phone: null,
        address: null,
        dob: null,
        avatar: null,
        password: null,
        role_id: null,
        deleted: false,
        blocked: false,
        facebook_auth: null,
        socket: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        google_auth: "104490012712564206960",
        code: null,
        created_at: "2024-07-03T09:55:15.850Z",
        updated_at: "2024-07-03T11:16:39.086Z",
      },
      {
        id: 3,
        first_name: "Trịnh Hoàng",
        last_name: "Quân",
        full_name: "Trịnh Hoàng Quân",
        nick_name: "Quân Trịnh Hoàng",
        email: "quanbkk65@gmail.com",
        phone: null,
        password: null,
        address: null,
        avatar: null,
        role_id: null,
        deleted: false,
        socket: null,
        blocked: false,
        facebook_auth: null,
        dob: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        google_auth: "110855109246208677704",
        code: null,
        created_at: "2024-07-04T03:08:06.431Z",
        updated_at: "2024-07-04T03:08:06.431Z",
      },
      {
        id: 4,
        first_name: "Võ Nguyên",
        last_name: "Hoàng",
        full_name: "Võ Nguyên Hoàng",
        nick_name: "dekisugi",
        email: "nguyenhoang@gmail.com",
        phone: "0586646623",
        address: "Thon noi-Thuong Lam-My Duc-Ha Noi",
        password:
          "$2a$10$eMEyY0hhVqBGHASjqTtRH.I3jnhNGN0G2YlX49QW8w9Q8LhjyAQ6W",
        avatar: null,
        role_id: null,
        dob: null,
        deleted: false,
        blocked: false,
        socket: null,
        facebook_auth: null,
        google_auth: null,
        code: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        created_at: "2024-07-03T08:11:20.473Z",
        updated_at: "2024-07-03T08:11:20.473Z",
      },
      {
        id: 5,
        first_name: "Lê Hoàng",
        last_name: "Long",
        full_name: "Lê Hoàng long",
        nick_name: "yasuo",
        email: "hoanglong@gmail.com",
        phone: "0358478659",
        address: "Thon noi-Thuong Lam-My Duc-Ha Noi",
        password:
          "$2a$10$eMEyY0hhVqBGHASjqTtRH.I3jnhNGN0G2YlX49QW8w9Q8LhjyAQ6W",
        avatar: null,
        role_id: null,
        dob: null,
        deleted: false,
        blocked: false,
        socket: null,
        facebook_auth: null,
        google_auth: null,
        code: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        created_at: "2024-07-03T08:11:20.473Z",
        updated_at: "2024-07-03T08:11:20.473Z",
      },
      {
        id: 6,
        first_name: "Đỗ Bá",
        last_name: "Long",
        full_name: "Đỗ Bá Long",
        nick_name: "dragon",
        email: "nglong@gmail.com",
        phone: "0758459623",
        address: "Thon noi-Thuong Lam-My Duc-Ha Noi",
        password:
          "$2a$10$eMEyY0hhVqBGHASjqTtRH.I3jnhNGN0G2YlX49QW8w9Q8LhjyAQ6W",
        avatar: null,
        role_id: null,
        dob: null,
        deleted: false,
        blocked: false,
        socket: null,
        facebook_auth: null,
        google_auth: null,
        code: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        created_at: "2024-07-03T08:11:20.473Z",
        updated_at: "2024-07-03T08:11:20.473Z",
      },
      {
        id: 7,
        first_name: "Lê Thị Thu",
        last_name: "Hà",
        full_name: "Lê Thị Thu Hà",
        nick_name: "conan",
        email: "thuha@gmail.com",
        phone: "0787459486",
        address: "Thon noi-Thuong Lam-My Duc-Ha Noi",
        password:
          "$2a$10$eMEyY0hhVqBGHASjqTtRH.I3jnhNGN0G2YlX49QW8w9Q8LhjyAQ6W",
        avatar: null,
        role_id: null,
        dob: null,
        deleted: false,
        blocked: false,
        socket: null,
        facebook_auth: null,
        google_auth: null,
        code: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        created_at: "2024-07-03T08:11:20.473Z",
        updated_at: "2024-07-03T08:11:20.473Z",
      },
      {
        id: 8,
        first_name: "Cao Diễm",
        last_name: "Quỳnh",
        full_name: "Cao Diễm Quỳnh",
        nick_name: "cdm",
        email: "diemquynh@gmail.com",
        phone: "0781556416",
        address: "Thon noi-Thuong Lam-My Duc-Ha Noi",
        password:
          "$2a$10$eMEyY0hhVqBGHASjqTtRH.I3jnhNGN0G2YlX49QW8w9Q8LhjyAQ6W",
        avatar: null,
        role_id: null,
        dob: null,
        deleted: false,
        blocked: false,
        socket: null,
        facebook_auth: null,
        google_auth: null,
        code: null,
        about: "I am fresher web developer!",
        last_online: "2024-07-08T08:11:20.473Z",
        created_at: "2024-07-03T08:11:20.473Z",
        updated_at: "2024-07-03T08:11:20.473Z",
      },
    ]);
    await queryInterface.sequelize.query(`
    SELECT setval(
      pg_get_serial_sequence('users', 'id'), 
      (SELECT MAX(id) FROM "users")
    );
  `);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("users", null, {});
  },
};
